all:
  hosts:
    node1:
      ansible_host: 10.0.1.86
      ip: 10.0.1.86
      access_ip: 10.0.1.86
    node2:
      ansible_host: 10.0.3.233
      ip: 10.0.3.233
      access_ip: 10.0.3.233
    node3:
      ansible_host: 10.0.2.176
      ip: 10.0.2.176
      access_ip: 10.0.2.176
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
